CREATE SCHEMA CORE;

-- DROPS
DROP TABLE CORE.TB_ADDRESS IF EXISTS;
DROP TABLE CORE.TB_EMAIL IF EXISTS;
DROP TABLE CORE.TB_MERCHANT IF EXISTS;
DROP TABLE CORE.TB_MERCHANT_ADDRESS IF EXISTS;
DROP TABLE CORE.TB_MERCHANT_EMAIL IF EXISTS;
DROP TABLE CORE.TB_MERCHANT_PHONE IF EXISTS;
DROP TABLE CORE.TB_PHONE IF EXISTS;

DROP SEQUENCE IF EXISTS CORE.SEQ_MERCHANT;
DROP SEQUENCE IF EXISTS CORE.SEQ_ADDRESS;
DROP SEQUENCE IF EXISTS CORE.SEQ_PHONE;
DROP SEQUENCE IF EXISTS CORE.SEQ_EMAIL;


-- CREATE

CREATE SEQUENCE CORE.SEQ_MERCHANT   INCREMENT BY 1 NO MINVALUE NO MAXVALUE START WITH 1;
CREATE SEQUENCE CORE.SEQ_ADDRESS    INCREMENT BY 1 NO MINVALUE NO MAXVALUE START WITH 1;
CREATE SEQUENCE CORE.SEQ_PHONE      INCREMENT BY 1 NO MINVALUE NO MAXVALUE START WITH 1;
CREATE SEQUENCE CORE.SEQ_EMAIL      INCREMENT BY 1 NO MINVALUE NO MAXVALUE START WITH 1;

CREATE TABLE CORE.TB_ADDRESS (
  CD_SEQ_ADDRESS  numeric(19, 0) NOT NULL,
  NU_ADDRESS      varchar(10),
  DS_COMPLEMENT   varchar(100),
  CD_UF           varchar(100) NOT NULL,
  CD_CITY         varchar(100) NOT NULL,
  DS_ADDRESS      varchar(100) NOT NULL,
  CD_NEIGHBORHOOD varchar(100) NOT NULL,
  CD_ZIPCODE      varchar(100) NOT NULL,
  DT_INSERT       timestamp NOT NULL,
  DT_LAST_UPDATE  timestamp NOT NULL,
  PRIMARY KEY (CD_SEQ_ADDRESS));

CREATE TABLE CORE.TB_EMAIL (
  CD_SEQ_EMAIL numeric(19, 0) NOT NULL,
  DS_EMAIL     varchar(255) NOT NULL,
  DT_INSERT    timestamp NOT NULL,
  DT_LAST_UPDATE  timestamp NOT NULL,
  PRIMARY KEY (CD_SEQ_EMAIL));

CREATE TABLE CORE.TB_MERCHANT (
  CD_SEQ_MERCHANT numeric(19, 0) NOT NULL,
  NM_MERCHANT     varchar(100) NOT NULL,
  NU_DOCUMENT     varchar(14) NOT NULL,
  CD_SEQ_ADDRESS  numeric(19, 0) NOT NULL,
  DT_INSERT       timestamp NOT NULL,
  DT_LAST_UPDATE  timestamp NOT NULL,
  PRIMARY KEY (CD_SEQ_MERCHANT));

CREATE TABLE CORE.TB_MERCHANT_EMAIL (
  CD_SEQ_MERCHANT numeric(19, 0) NOT NULL,
  CD_SEQ_EMAIL    numeric(19, 0) NOT NULL,
  PRIMARY KEY (CD_SEQ_MERCHANT,
  CD_SEQ_EMAIL));

CREATE TABLE CORE.TB_MERCHANT_PHONE (
  CD_SEQ_MERCHANT numeric(19, 0) NOT NULL,
  CD_SEQ_PHONE    numeric(19, 0) NOT NULL,
  PRIMARY KEY (CD_SEQ_MERCHANT,
  CD_SEQ_PHONE));

CREATE TABLE CORE.TB_PHONE (
  CD_SEQ_PHONE   numeric(19, 0) NOT NULL,
  NU_DDD         varchar(2) NOT NULL,
  NU_PHONE       varchar(9) NOT NULL,
  TP_PHONE       varchar(20) NOT NULL CHECK('RESIDENCIAL','COMERCIAL','CELULAR'),
  DT_INSERT      timestamp NOT NULL,
  DT_LAST_UPDATE timestamp NOT NULL,
  PRIMARY KEY (CD_SEQ_PHONE));

ALTER TABLE CORE.TB_MERCHANT_EMAIL ADD CONSTRAINT FKTB_MERCHAN511228 FOREIGN KEY (CD_SEQ_EMAIL) REFERENCES CORE.TB_EMAIL (CD_SEQ_EMAIL);
ALTER TABLE CORE.TB_MERCHANT_EMAIL ADD CONSTRAINT FKTB_MERCHAN923275 FOREIGN KEY (CD_SEQ_MERCHANT) REFERENCES CORE.TB_MERCHANT (CD_SEQ_MERCHANT);
ALTER TABLE CORE.TB_MERCHANT_PHONE ADD CONSTRAINT FKTB_MERCHAN604780 FOREIGN KEY (CD_SEQ_PHONE) REFERENCES CORE.TB_PHONE (CD_SEQ_PHONE);
ALTER TABLE CORE.TB_MERCHANT_PHONE ADD CONSTRAINT FKTB_MERCHAN899887 FOREIGN KEY (CD_SEQ_MERCHANT) REFERENCES CORE.TB_MERCHANT (CD_SEQ_MERCHANT);

ALTER TABLE CORE.TB_MERCHANT ADD CONSTRAINT FKTB_MERCHAN513250 FOREIGN KEY (CD_SEQ_ADDRESS) REFERENCES CORE.TB_ADDRESS (CD_SEQ_ADDRESS);
